---
services:
  app:
    container_name: ip-change-watcher
    build:
      context: .
      dockerfile: Dockerfile
  kafka-broker:  # Local Kafka broker
    image: confluentinc/cp-server:7.6.1
    container_name: kafka-broker
    depends_on:
      - kafka-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://kafka-broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      CONFLUENT_TELEMETRY_ENABLED: "false"
      CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      CONFLUENT_TELEMETRY_ENABLED: "false"
      CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: kafka-schema-registry
    depends_on:
      - kafka-broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  kafka-gui:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on:
      - kafka-broker
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka-broker:9092
